// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCIdJbXSs6wtLxDrffbqKggPT4bXlC0KCQ",
    authDomain: "logmonster-51e0a.firebaseapp.com",
    databaseURL: "https://logmonster-51e0a-default-rtdb.firebaseio.com",
    projectId: "logmonster-51e0a",
    storageBucket: "logmonster-51e0a.appspot.com",
    messagingSenderId: "824799785966",
    appId: "1:824799785966:web:fd90635c2180e3750c54ff",
    measurementId: "G-0P6ZT5GXPL",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRy9uC9me-smzDzfTXvLPRz7vdgWBlPTs',
    appId: '1:537053467187:android:4e88516ee2fb4e8fa10946',
    messagingSenderId: '537053467187',
    projectId: 'assn-a0d53',
    databaseURL: 'https://assn-a0d53-default-rtdb.firebaseio.com',
    storageBucket: 'assn-a0d53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lH_NfnRdwkHpk-7b7-xnN3trlDvZZ-c',
    appId: '1:824799785966:ios:c3871cbcad9e6f360c54ff',
    messagingSenderId: '824799785966',
    projectId: 'logmonster-51e0a',
    storageBucket: 'assn-a0d53.appspot.com',
    androidClientId:
        '537053467187-0acu2c6i63n7je0lps8lujss0d0qj42b.apps.googleusercontent.com',
    iosClientId:
        '537053467187-78e1o138ik61horaecgc2cms6tfg998a.apps.googleusercontent.com',
    iosBundleId: 'com.assn.seat.assn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lH_NfnRdwkHpk-7b7-xnN3trlDvZZ-c',
    appId: '1:537053467187:ios:2516baecc911fad2a10946',
    messagingSenderId: '537053467187',
    projectId: 'assn-a0d53',
    databaseURL: 'https://assn-a0d53-default-rtdb.firebaseio.com',
    storageBucket: 'assn-a0d53.appspot.com',
    androidClientId:
        '537053467187-0acu2c6i63n7je0lps8lujss0d0qj42b.apps.googleusercontent.com',
    iosClientId:
        '537053467187-78e1o138ik61horaecgc2cms6tfg998a.apps.googleusercontent.com',
    iosBundleId: 'com.assn.seat.assn',
  );
}
