// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZTu08PLw-gpOuWHKw1BM7lBTIZQLoyK0',
    appId: '1:761267722872:web:cc5c8c177559390204eb8d',
    messagingSenderId: '761267722872',
    projectId: 'cryptic-a727a',
    authDomain: 'cryptic-a727a.firebaseapp.com',
    storageBucket: 'cryptic-a727a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8eaq1ifG5OE3MhkS_l0_FwawYjjulfc',
    appId: '1:761267722872:android:9d5ae5c1ce3240e604eb8d',
    messagingSenderId: '761267722872',
    projectId: 'cryptic-a727a',
    storageBucket: 'cryptic-a727a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRWCu5G6UnUy8MJ1JP7NFCjsFWAoPAbk',
    appId: '1:761267722872:ios:9e00bd71c022e34a04eb8d',
    messagingSenderId: '761267722872',
    projectId: 'cryptic-a727a',
    storageBucket: 'cryptic-a727a.appspot.com',
    iosBundleId: 'com.criptyc.transfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYRWCu5G6UnUy8MJ1JP7NFCjsFWAoPAbk',
    appId: '1:761267722872:ios:ba70e82b896c6e2304eb8d',
    messagingSenderId: '761267722872',
    projectId: 'cryptic-a727a',
    storageBucket: 'cryptic-a727a.appspot.com',
    iosBundleId: 'com.example.edmonscan.RunnerTests',
  );
}
