// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdJbXSs6wtLxDrffbqKggPT4bXlC0KCQ',
    appId: '1:824799785966:web:58d583b7edc562f40c54ff',
    messagingSenderId: '824799785966',
    projectId: 'logmonster-51e0a',
    authDomain: 'logmonster-51e0a.firebaseapp.com',
    databaseURL: 'https://logmonster-51e0a-default-rtdb.firebaseio.com',
    storageBucket: 'logmonster-51e0a.appspot.com',
    measurementId: 'G-7T960CYL90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyuJZq4O_LrF2JEUXR5U7iWx3LzYJ5Xo',
    appId: '1:824799785966:android:52c405cd284853570c54ff',
    messagingSenderId: '824799785966',
    projectId: 'logmonster-51e0a',
    databaseURL: 'https://logmonster-51e0a-default-rtdb.firebaseio.com',
    storageBucket: 'logmonster-51e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjljVo1RUUAC2iMciuKT-aN8uzRuFrQ-E',
    appId: '1:824799785966:ios:6756a2a4dd2468230c54ff',
    messagingSenderId: '824799785966',
    projectId: 'logmonster-51e0a',
    databaseURL: 'https://logmonster-51e0a-default-rtdb.firebaseio.com',
    storageBucket: 'logmonster-51e0a.appspot.com',
    iosClientId: '824799785966-qdot2ddlkm5g0rvj733p6jbgtju7mdu6.apps.googleusercontent.com',
    iosBundleId: 'com.edmon.scan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjljVo1RUUAC2iMciuKT-aN8uzRuFrQ-E',
    appId: '1:824799785966:ios:ef3742df3ac63ddb0c54ff',
    messagingSenderId: '824799785966',
    projectId: 'logmonster-51e0a',
    databaseURL: 'https://logmonster-51e0a-default-rtdb.firebaseio.com',
    storageBucket: 'logmonster-51e0a.appspot.com',
    iosClientId: '824799785966-o1ps93i08g4ktspvs9ilgptobb7o2fhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.edmonscan.RunnerTests',
  );
}
